apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: javaee-store
  namespace: default
spec:
  replicas: 2
  template:
    metadata:
      name: javaee-store
      labels:
        app: javaee-store
    spec:
      containers:
      - name: javaee-store
        env:
          - name: POSTGRES_USER
            valueFrom:
              configMapKeyRef:
                name: postgres-config
                key: postgres_user
          - name: POSTGRES_PASSWORD
            valueFrom:
              configMapKeyRef:
                name: postgres-config
                key: postgres_password
          - name: POSTGRES_HOST
            valueFrom:
              configMapKeyRef:
                name: hostname-config
                key: postgres_host
        image: hillmerch/javaee-store:4
        imagePullPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: javaee-store
spec:
  type: LoadBalancer
  ports:
    - port: 9080
  selector:
    app: javaee-store